# Generated by Django 3.1.1 on 2020-09-10 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200910_1512'),
        ('cart', '0002_auto_20200910_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='nmb',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.DeleteModel(
            name='ProductInOrder',
        ),
    ]
