# Generated by Django 3.1.1 on 2020-09-10 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_remove_order_product'),
        ('product', '0002_auto_20200910_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='order',
            field=models.ManyToManyField(to='cart.Order'),
        ),
    ]
