# Generated by Django 3.1.1 on 2020-09-10 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='order',
        ),
    ]
